# Generated by Django 6.1.1 on 2026-09-24 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=15)),
                ('file', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('reserve_date', models.DateField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('services', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('explain', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=144, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=15)),
                ('file', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('reserve_date', models.DateField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('services', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('submit', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.CharField(blank=True, choices=[('cancelled', 'کنسل شد'), ('consent', 'وقت مشاوره داره'), ('pending', 'در انتظار بیعانه'), ('done', 'انجام شده'), ('report', 'خبر میدم'), ('wasdone', 'انجام داده'), ('notaswer', 'جواب نداده')], max_length=20, null=True)),
                ('enter_choices', models.CharField(blank=True, choices=[('new_enter', 'ورودی جدید'), ('old_enter', 'ورودی قدیم'), ('instagram', 'اینستاگرام'), ('whatsapp', 'ورودی واتساپ'), ('google', 'گوگل'), ('introduce', 'معرفی'), ('bale', 'بله'), ('message', 'پیامک'), ('lucky_wheel', 'گردونه شانس'), ('rubika', 'روبیکا'), ('nini_site', 'نی نی سایت')], max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=122, null=True)),
                ('explain', models.TextField()),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CallCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('persons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='reserve_station.personal')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_before', models.ImageField(blank=True, null=True, upload_to='before/')),
                ('img_after', models.ImageField(blank=True, null=True, upload_to='after/')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='reserve_station.submitpersonal')),
            ],
        ),
    ]
