# Generated by Django 6.1.1 on 2026-09-21 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=15)),
                ('file', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('reserve_date', models.DateField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('services', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('submit', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubmitPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=15)),
                ('file', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('reserve_date', models.DateField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('services', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_before', models.ImageField(blank=True, null=True, upload_to='before/')),
                ('img_after', models.ImageField(blank=True, null=True, upload_to='after/')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='reserve_station.submitpersonal')),
            ],
        ),
    ]
