# Generated by Django 6.1.1 on 2026-09-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_station', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='status',
            field=models.CharField(blank=True, choices=[('cancelled', 'کنسل شد'), ('consent', 'وقت مشاوره داره'), ('pending', 'در انتظار بیعانه'), ('done', 'انجام شده'), ('report', 'خبر میدم'), ('wasdone', 'انجام داده'), ('notaswer', 'جواب نداده')], max_length=20, null=True),
        ),
    ]
