# Generated by Django 6.1.1 on 2026-09-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_station', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalpicture',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
