# Generated by Django 6.1.1 on 2026-09-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_station', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='FollowUp',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='consent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
