# Generated by Django 6.1.1 on 2026-09-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_station', '0002_personal_followup_personal_consent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='FollowUp',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='consent',
        ),
        migrations.AddField(
            model_name='personal',
            name='status',
            field=models.CharField(blank=True, choices=[('cancelled', 'کنسل شد'), ('consent', 'وقت مشاوره داره'), ('pending', 'جواب نداده'), ('done', 'انجام شده')], max_length=20, null=True),
        ),
    ]
